### ISSUE TITLE
Hello fellow Neo4j rubist!

### ISSUE THREAD

**Issue by cheerfulstoic** [hiroponz/neo4r#1]
I ran across your gem and it seems to do a lot of the same stuff we're doing over in the neo4j gem:

https://github.com/neo4jrb/neo4j

Though some of the other stuff is being done by the neo4j-core gem:

https://github.com/neo4jrb/neo4j-core

I'm one of the maintainers of these gems (@subvertallchris is the other) and they're pretty mature now, so maybe you'd like to use them instead?  We're happy to answer any questions!  We've got a Gitter chat channel that we normally hang around in:

https://gitter.im/neo4jrb/neo4j

**Comment by hiroponz** [comment]
Hello, @cheerfulstoic 

You are right. I was used https://github.com/neo4jrb/neo4j.
I needed to migrate to MRI from JRuby, but it depended on JRuby.
So I wrote this gem to replace it.
If the neo4j gem was running on MRI, I use it instead.

My system is:
- MRI 2.1
- Rails 3.2

**Comment by cheerfulstoic** [comment]
Ah, yeah.  There are a lot of out of date tutorials/information out there.  The neo4j/neo4j-core gems have supported both JRuby and MRI since version 3.0 (since about October 2014).  The current version is 5.0 and has lots of improvements since 3.0 as well.

**Comment by cheerfulstoic** [comment]
Also to clarify if you use MRI you can only use "server" mode (which makes sense).  With JRuby you can use either server or embedded mode

**Comment by hiroponz** [comment]
Thanks, @cheerfulstoic
I'm going to try the neo4j gem.

**Comment by cheerfulstoic** [comment]
Great, let us know if you have any questions!  I'll close this issue now ;)
